services:
  db:
    image: postgres
    hostname: postgres
    volumes:
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './data/db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=var/lib/postgres/data/pgdata
  web:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db